In [33]:
from time import sleep
import numpy as np
import random

In [34]:
def create_board():
  return (np.array([[0,0,0],[0,0,0],[0,0,0]]))

In [43]:
def possibilities(board):
  l=[]
  for i in range(len(board)):
    for j in range(len(board)):
      if board[i][j]==0:
        l.append((i,j))
  return l

In [36]:
def random_place(board,player):
  selection=possibilities(board)
  current_location=random.choice(selection)
  board[current_location]=player
  return board

In [50]:
def row_win(board,player):
  for x in range(len(board)):
    win=True
    for y in range(len(board)):
      if board[x,y]!=player:
        win=False
        continue
    if win==True:
       return (win)
  return (win)

In [53]:
def col_win(board,player):
  for x in range(len(board)):
    win=True
    for y in range(len(board)):
      if board[y,x]!=player:
        win=False
        continue
    if win==True:
       return (win)
  return (win)

In [54]:
def diag_win(board,player):
  win=True
  y=0
  for x in range(len(board)):
   if board[x,x]!=player:
    win=False
  if win:
    return win

  win=True
  for x in range(len(board)):
    y=len(board)-1-x
    if board[x,y]!=player:
      win=False
  return (win)

In [46]:
def evaluate(board):
  winner=0
  for player in [1,2]:
    if(row_win(board,player) or col_win(board,player) or diag_win(board,player)):
      winner=player
  if np.all(board!=0) and winner==0:
    winner=-1
  return winner

In [48]:
def play_game():
  board,winner,counter=create_board(),0,1
  print(board)
  sleep(2)
  while(winner==0):
    for player in [1,2]:
      board=random_place(board,player)
      print("board after " + str(counter) + " move")
      print(board)
      counter+=1
      winner=evaluate(board)
      if winner!=0:
        break
  return winner

In [55]:
play_game()

[[0 0 0]
 [0 0 0]
 [0 0 0]]
board after 1 move
[[0 0 1]
 [0 0 0]
 [0 0 0]]
board after 2 move
[[0 0 1]
 [0 2 0]
 [0 0 0]]
board after 3 move
[[0 0 1]
 [0 2 0]
 [0 0 1]]
board after 4 move
[[0 0 1]
 [0 2 0]
 [0 2 1]]
board after 5 move
[[1 0 1]
 [0 2 0]
 [0 2 1]]
board after 6 move
[[1 0 1]
 [0 2 2]
 [0 2 1]]
board after 7 move
[[1 1 1]
 [0 2 2]
 [0 2 1]]


1